/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function init(path: string): void

export declare function opcodeList(): Array<string>

export declare function step(): void

export declare function stepBack(): void
